#pragma once
enum State {
	STATE_NULL,
	STATE_TITLE,
	STATE_GAME,
	STATE_WIN,
	STATE_EXIT
};

enum TileSprite {
	UNLOCKED_TILE_BLANK = 0,
	UNLOCKED_TILE_1 = 1,
	UNLOCKED_TILE_2 = 2,
	UNLOCKED_TILE_3 = 3,
	UNLOCKED_TILE_4 = 4,
	UNLOCKED_TILE_5 = 5,
	UNLOCKED_TILE_6 = 6,
	UNLOCKED_TILE_7 = 7,
	UNLOCKED_TILE_8 = 8,
	UNLOCKED_TILE_9 = 9,
	LOCKED_TILE_BLANK = 10,
	LOCKED_TILE_1 = 11,
	LOCKED_TILE_2 = 12,
	LOCKED_TILE_3 = 13,
	LOCKED_TILE_4 = 14,
	LOCKED_TILE_5 = 15,
	LOCKED_TILE_6 = 16,
	LOCKED_TILE_7 = 17,
	LOCKED_TILE_8 = 18,
	LOCKED_TILE_9 = 19,
	TILE_SPRITE_TOTAL = 20
};
